### ISSUE TITLE
after registration login is not working

### ISSUE THREAD

**Issue by Piruthivirajan** [Baeldung/spring-security-registration#100]
Invalid Credentials issue after login

**Comment by maibin** [comment]
@Piruthivirajan can you please provide more details about which article you are referring to, what are the steps, etc.? It's hard to replicate your issue without having some details about it.

**Comment by eugenp** [comment]
Cool, closing this one, but if you do have more details, @Piruthivirajan  - feel free to re-open it. 
Thanks, 
Eugen.
