### ISSUE TITLE
Encoded password does not look like BCrypt with inmemory authenticaiton using Bcrypt password encoder

### ISSUE THREAD

**Issue by prashdeep** [Baeldung/spring-security-registration#112]
This issue is still reproducible with Spring boot version 2.2.0 and Spring security 5.2.0 version with inmemory authentication.

```
 @Autowired
    public void configureGlobal(AuthenticationManagerBuilder authenticationManagerBuilder) throws Exception {
        authenticationManagerBuilder
                .inMemoryAuthentication()
                .withUser("hari")
                .password("welcome")
                .roles("USER")
                .and()
                .withUser("kiran")
                .password("testing")
                .roles("USER", "ADMIN")
                .and()
                .passwordEncoder(passwordEncoder());

  @Bean
    public BCryptPasswordEncoder passwordEncoder(){
        return new BCryptPasswordEncoder();
    }
```

2019-11-03 19:10:50.962  WARN 14504 --- [nio-8080-exec-1] o.s.s.c.bcrypt.BCryptPasswordEncoder     : Encoded password does not look like BCrypt

_Originally posted by @prashdeep in https://github.com/Baeldung/spring-security-registration/issues/65#issuecomment-549137956_

**Comment by fanatixan** [comment]
Hello @prashdeep,

Could you please point to the class which contains this configuration?

Thanks.

**Comment by prashdeep** [comment]
This is not an issue. I did not store the encoded password.
