### ISSUE TITLE
Why some table names are Upper Camer Case. And some are underscore case

### ISSUE THREAD

**Issue by princegoyal1987** [Baeldung/spring-security-registration#113]
This is not an issue, But more of a question. 

Is there any particular reason why there are two conventions in the table names? I can see these names:

- DeviceMetadata
- PasswordResetToken
- Privilege
- Role
- VerificationToken
- hibernate_sequence
- roles_privileges
- user_account
- users_roles 

Is it a convention or you just didn't care to change the names?

**Comment by lor6** [comment]
Hi @princegoyal1987  The upper case names are the default names generated by JPA. The other table names were set manually, like: https://github.com/Baeldung/spring-security-registration/blob/master/src/main/java/com/baeldung/persistence/model/Role.java#L24 

You're right, using a single convention would be a better practice.
