### ISSUE TITLE
Double login path

### ISSUE THREAD

**Issue by mitm001** [Baeldung/spring-security-registration#114]
I see a duplicate of /login* in the WebSecurityConfigurerAdapter.

https://github.com/Baeldung/spring-security-registration/blob/b17232a3857e0cd55a21d377e2c58d77748e7ae0/src/main/java/org/baeldung/spring/SecSecurityConfig.java#L80

Is second erroneous and there should only be one /login** or just /login*?

**Comment by dkapil** [comment]
Thanks for your contribution @mitm001 . We have fixed this issue.
