### ISSUE TITLE
In Entities, You are using direct field access (instead  of accessor)

### ISSUE THREAD

**Issue by princegoyal1987** [Baeldung/spring-security-registration#115]
I can see in Role.java you are doing this:

```
    public boolean equals(final Object obj) {
        --- Some Checks---
        final Role role = (Role) obj;
        if (!name.equals(role.name)) {
            return false;
        }
        return true;
    }
```

According to Hibernate conventions you shouldn't do it you should always call getter.

So you should do:
```
    public boolean equals(final Object obj) {
        --- Some Checks---
        final Role role = (Role) obj;
        if (!getName().equals(role.getName())) {
            return false;
        }
        return true;
    }
```

This is in referece to Proxy-Pitfalls-1:
https://xebia.com/blog/advanced-hibernate-proxy-pitfalls/

Since you are an expert. I want to know your opinion on this.

**Comment by dkapil** [comment]
Thanks for your contribution @princegoyal1987 . We have fixed this issue.
