### ISSUE TITLE
better way to access h2 endpoint in dev profile

### ISSUE THREAD

**Issue by phxism** [Baeldung/spring-security-registration#144]
in SecSecurityConfig.java`  .headers().frameOptions().disable();` is not a very good sample,which will reduce system security .there is a better way i found on the internet [https://dzone.com/articles/using-the-h2-database-console-in-spring-boot-with [COMMENT from Rob Winch] ](https://dzone.com/articles/using-the-h2-database-console-in-spring-boot-with) 

> Thanks for the write up. It seems it would be quite a bit easier & secure to use security.ignored=/console/** along with a profile. This way users don't accidentally have CSRF and the security headers disabled in production. See https://github.com/rwinch/spring-security-sample/tree/h2-console (note the h2-console branch) for a complete example.

**Comment by sampada07** [comment]
Thanks @phxism for the useful suggestion. We've added the fix.
Cheers!
