### ISSUE TITLE
Broken code in UserService.java

### ISSUE THREAD

**Issue by daxyonis** [Baeldung/spring-security-registration#151]
Hello, the project does not compile due to an error in src/main/java/com/baeldung/service/UserService.java : the variable env identifier type is missing.

**Comment by JDHL** [comment]
Error is at line 73 in UserSerivce as the parameter env is missing an identifier.

The env field is looking like this:
`@Autowired private env;`

What it should be:
`@Autowired private Environment env`

It is also necessary to include the Environment class from the Spring core package in the import.

**Comment by koval4uk** [comment]
Open pull request - https://github.com/Baeldung/spring-security-registration/pull/152

**Comment by sampada07** [comment]
Thanks @koval4uk for the fix. We've merged the PR.
