### ISSUE TITLE
MFA keeps failing: totp validation always returns false

### ISSUE THREAD

**Issue by xtamil2002** [Baeldung/spring-security-registration#156]
I have followed the code and setup a new account and enabled MFA.  However the totp verification keeps returning false.  I have tried time sync on the Google Authenticator app.  What else could be wrong?

**Comment by lor6** [comment]
@xtamil2002  You'll need to check the console logs or debug the verification process to get more information.

**Comment by kwoyke** [comment]
Closed due to lack of activity.
