### ISSUE TITLE
Login form submits to unexisting action

### ISSUE THREAD

**Issue by ur-ko** [Baeldung/spring-security-registration#158]
After entering user/pass on login page (http://localhost:8081/login or http://localhost:8081/customLogin) and submitting form, user is presented with empty page.
Response for this request is 405, in the Java log I can see "Request method 'POST' not supported" 

Downloaded latest code from the master branch, changed config to use mysql, disabled H2, registered few test users.

**Comment by gashukov** [comment]
Same problem.
Can't fix this for days.

**Comment by ur-ko** [comment]
> 
> 
> Same problem.
> Can't fix this for days.

Try delete H2Config.java, that should fix it.

**Comment by kwoyke** [comment]
We have verified the login functionality currently works fine.
