### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by hamishlawson** [Baeldung/spring-security-registration#176]
The following tests fail:

- com.baeldung.test.RegistrationControllerIntegrationTest
   - testRegistrationConfirm
- com.baeldung.test.RegistrationPasswordLiveTest
   - givenInvalidPassword_thenBadRequest

**Comment by kwoyke** [comment]
Hi @hamishlawson,
We fixed the failing RegistrationControllerIntegrationTest.
For the RegistrationPasswordLiveTest you need to set up mail account in application.properties as mentioned [here](https://github.com/anuragkumawat/spring-security-registration/tree/master#set-up-email), also you need to turn on "Less secure app access" in settings of Google account (if using google account for sending mail), along with disabling 2-step verification of google account. 
Hope this helps.
