### ISSUE TITLE
Make LoggedUser serializable or don't store it in the session.

### ISSUE THREAD

**Issue by sara4cristina** [Baeldung/spring-security-registration#181]
Hi! 

I've just checked this project using SonarQube and I found some little bugs in it. 
Hope it helps!

![image](https://user-images.githubusercontent.com/94064021/173406146-03fe8fe3-acea-41c8-8886-5d7225e0cf72.png)

This appear in src/main/java/com/baeldung/security/MyCustomLoginAuthenticationSuccessHandler.java
and
src/main/java/com/baeldung/spring/SetupDataLoader.java.

_Why is this an issue?_

**Non-serializable objects should not be stored in "HttpSession" objects**

If you have no intention of writting an HttpSession object to file, then storing non-serializable objects in it may not seem like a big deal. But whether or not you explicitly serialize the session, it may be written to disk anyway, as the server manages its memory use in a process called "passivation". Further, some servers automatically write their active sessions out to file at shutdown & deserialize any such sessions at startup.

The point is, that even though HttpSession does not extend Serializable, you must nonetheless assume that it will be serialized, and understand that if you’ve stored non-serializable objects in the session, errors will result.

**Comment by kwoyke** [comment]
Thanks for the feedback. We'll take a look into this.
