### ISSUE TITLE
A successful login shouldn't reset the attempt counter

### ISSUE THREAD

**Issue by SentretC** [Baeldung/spring-security-registration#197]
Otherwise an attacker that owns one account can attack others by log into their own account once every 9 brute force attempts to avoid getting blocked.

**Comment by ulisseslima** [comment]
Hey, @SentretC.

Thanks for the feedback. We'll take this to the team and update the article if necessary.

**Comment by lor6** [comment]
The article and code have been updated to remove the counter reset on successful login.
