### ISSUE TITLE
Error in POM

### ISSUE THREAD

**Issue by oleersoy** [Baeldung/spring-security-registration#22]
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.thymeleaf.extras:thymeleaf-extras-springsecurity4:jar -> duplicate declaration of version (?) @ line 64, column 21
[FATAL] Non-readable POM /home/ole/Sandbox/pom.xml: input contained no data @ /home/ole/Sandbox/pom.xml

**Comment by oleersoy** [comment]
Section `2fa` contains the duplicated dependency.

**Comment by eugenp** [comment]
Thanks for the heads up @oleersoy. 
Fixed. Cheers, 
Eugen.

**Comment by oleersoy** [comment]
Awesome - Thanks Eugen!  Huge fan of your articles BTW.  Brilliant work!

**Comment by eugenp** [comment]
I'm glad you're enjoying the site @oleersoy  - and of course thanks for the help here. 
Cheers, 
Eugen.
