### ISSUE TITLE
Shouldn't ROLE_ be returned in MyUserDetailsService.getAuthorities

### ISSUE THREAD

**Issue by leonroy** [Baeldung/spring-security-registration#35]
My knowledge is a little sketchy as far as Spring Security goes but looking at [https://github.com/Baeldung/spring-security-registration/blob/master/src/main/java/org/baeldung/security/MyUserDetailsService.java#L63](getAuthorities) wouldn't it be better if the corresponding user's ROLE_XXX is added to the returned list of GrantedAuthority?

ie.

For **ROLE_ADMIN** a collection containing:

`WRITE_PRIVILEGE, READ_PRIVILEGE, CHANGE_PASSWORD_PRIVILEGE, ROLE_ADMIN` would be returned

For **ROLE_USER** a collection containing:

`READ_PRIVILEGE, CHANGE_PASSWORD_PRIVILEGE, ROLE_ADMIN` would be returned

That way both hasAuthority and hasRole would be usable. At the moment the latter prefixes ROLE_ to any PRIVILEGE check.

**Comment by eugenp** [comment]
Well, the general idea here is to have a better structure for roles and privileges. That means two things. 
First - it means having a hierarchy - where role is simply a holder of privileges. So roles themselves should never be used or needed directly. 
Second, it also means letting go of the "role" terminology as the framework uses it. That's a historical artifact from the Acegi days and generally creates confusion. 

Hope that clears things up. 
Cheers, 
Eugen.
