### ISSUE TITLE
Bootstrap and static folder

### ISSUE THREAD

**Issue by pi-2r** [Baeldung/spring-security-registration#36]
HI there,

currently I try to apply a html theme with elements located in the "static" folder and with bootstrap and jquery from de maven.
On other project it works perfectly, there it does not load ... even with this line of code:

```
 <link th:href="@{/webjars/bootstrap/3.3.6/css/bootstrap.min.css}" rel="stylesheet" media="screen" />
  <link type="text/css" th:href="@{/css/style.default.css}" rel="stylesheet" media="screen"/>
```
How I fix it ?
thank you in advance

**Comment by eugenp** [comment]
Hey @pi-2r - let me see if I fully understand your problem here. 
You're running into this one on your own codebase? Or on this codebase here?

Cheers, 
Eugen.

**Comment by lor6** [comment]
If this is a Spring project, here's an article on serving static resources: http://www.baeldung.com/spring-mvc-static-resources
Spring Boot will automatically pick up resources in the /resources folder.
