### ISSUE TITLE
AuthenticationFailureListener and AuthenticationSuccessEventListener should use X-Forwarded-For address

### ISSUE THREAD

**Issue by andreiepure** [Baeldung/spring-security-registration#40]
Problem: the [AuthenticationFailureListener ](https://github.com/Baeldung/spring-security-registration/blob/master/src/main/java/org/baeldung/security/AuthenticationFailureListener.java) and [AuthenticationSuccessEventListener ](https://github.com/Baeldung/spring-security-registration/tree/master/src/main/java/org/baeldung/security) use the [WebAuthenticationDetails](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/WebAuthenticationDetails.java), which in turn uses `this.remoteAddress = request.getRemoteAddr();`

According to the [article ](http://www.baeldung.com/spring-security-block-brute-force-authentication-attempts), in cases of proxies, the X-Forwarded-For should be used. It might be a corner case, but as long as [MyUserDetailsService.java](https://github.com/Baeldung/spring-security-registration/blob/master/src/main/java/org/baeldung/security/MyUserDetailsService.java) uses  X-Forwarded-For, there should be some consistency.

Otherwise, the last IP will be blocked and MyUserDetailsService will retrieve the IP from X-Forwarded-For and the solution won't work as expected.

**Comment by eugenp** [comment]
Thanks for the feedback Andrei - looking into it.

**Comment by lor6** [comment]
This has been fixed.
