### ISSUE TITLE
Javax Validation Exception 

### ISSUE THREAD

**Issue by 1988gadocansey** [Baeldung/spring-security-registration#41]
Hi am using Springboot 1.5.3 with this tutorial and I had this exception
web - 2017-06-02 20:14:05,199 [http-nio-8081-exec-3] ERROR o.m.w.e.RestResponseEntityExceptionHandler - 500 Status Code
j.v.ValidationException: HV000028: Unexpected exception during isValid call.
	at o.h.v.i.e.c.ConstraintTree.validateSingleConstraint(ConstraintTree.java:451)
	at o.h.v.i.e.c.ConstraintTree.validateConstraints(ConstraintTree.java:127)
	at o.h.v.i.e.c.ConstraintTree.validateConstraints(ConstraintTree.java:87)
	at o.h.v.i.m.c.MetaConstraint.validateConstraint(MetaConstraint.java:73)
	at o.h.v.i.e.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:620)
	... 95 frames truncated
Caused by: j.l.NullPointerException: null
	at o.m.v.PasswordMatchesValidator.isValid(PasswordMatchesValidator.java:18)
	at o.h.v.i.e.c.ConstraintTree.validateSingleConstraint(ConstraintTree.java:448)
	... 99 common frames omitted

**Comment by eugenp** [comment]
Hey @1988gadocansey - can you give me a bit more info on this one?
What module are you running exactly?
And what are the steps you're running in order to hit this NPE?

**Comment by 1988gadocansey** [comment]
=========

## Login and Registration Example Project with Spring Security


### Relevant Articles: 
- [Spring Security Registration Tutorial](http://www.baeldung.com/spring-security-registration)
- [The Registration Process With Spring Security](http://www.baeldung.com/registration-with-spring-mvc-and-spring-security)
- [Registration – Activate a New Account by Email](http://www.baeldung.com/registration-verify-user-by-email)
- [Registration with Spring Security – Password Encoding](http://www.baeldung.com/spring-security-registration-password-encoding-bcrypt)
- [Spring Security – Roles and Privileges](http://www.baeldung.com/role-and-privilege-for-spring-security-registration)
- [Prevent Brute Force Authentication Attempts with Spring Security](http://www.baeldung.com/spring-security-block-brute-force-authentication-attempts)
- [Spring Security – Reset Your Password](http://www.baeldung.com/spring-security-registration-i-forgot-my-password)
- [Spring Security Registration – Resend Verification Email](http://www.baeldung.com/spring-security-registration-verification-email)
- [The Registration API becomes RESTful](http://www.baeldung.com/registration-restful-api)
- [Registration – Password Strength and Rules](http://www.baeldung.com/registration-password-strength-and-rules)
- [Updating your Password](http://www.baeldung.com/updating-your-password/)
- [Registration - Integrate reCAPTCHA](http://www.baeldung.com/spring-security-registration-captcha/)
- [Two Factor Auth with Spring Security](http://www.baeldung.com/spring-security-two-factor-authentication-with-soft-token)
- [Registration with Spring – Integrate reCAPTCHA](http://www.baeldung.com/spring-security-registration-captcha)
- [Purging Expired Tokens Generated By The Registration](http://www.baeldung.com/registration-token-cleanup)

### Build and Deploy the Project
```
mvn clean install
```

This is a Spring Boot project, so you can deploy it by simply using the main class: `Application.java`



### Set up MySQL
```
mysql -u root -p 
> CREATE USER 'tutorialuser'@'localhost' IDENTIFIED BY 'tutorialmy5ql';
> GRANT ALL PRIVILEGES ON *.* TO 'tutorialuser'@'localhost';
> FLUSH PRIVILEGES;
```


### Set up Email

You need to configure the email by renaming file "email.properties.sample" to "email.properties" and provide your own username and password.
You also need to use your own host, you can use Amazon or Google for example.
You may also setup an email server locally.  See "email.properties.localhost.sample" for more details.

**Comment by eugenp** [comment]
Hey @1988gadocansey - not sure I understand. I asked for a bit more info on how to reproduce the problem here and you pasted the readme file as an answer :)

**Comment by 1988gadocansey** [comment]
Sorry Sir, please wheres a screenshot of the exception i was trying to
explain. Anytime i try saving an entity or doing any database task



*Gad Kartey Ocansey*

*Senior Instructor*

*Computer Science Dept*


*Takoradi Polytechnic+233243348522, +233505284060*

*gad.ocansey@tpoly.edu.gh <gad.ocansey@tpoly.edu.gh>*

**Comment by eugenp** [comment]
Hmm - interesting - can you write a failing test for it? I'd like to have a way to reproduce it, and a PR might help. 
Cheers, 
Eugen.
