### ISSUE TITLE
Each time when event occurs, SetupDataLoader creates new admin 

### ISSUE THREAD

**Issue by Kvark900** [Baeldung/spring-security-registration#46]
When `hbm2ddl.auto=update` `SetupDataLoader ` creates new admin with the same details. Maybe there should be also method `createUserIfNotFound`?

**Comment by eugenp** [comment]
Hey @Kvark900 - looking into it, thanks for letting me know.

**Comment by eugenp** [comment]
Hey @Kvark900  - the changes are in - feel free to have a look. 
Cheers, 
Eugen.
