### ISSUE TITLE
Resend email if token is lost

### ISSUE THREAD

**Issue by TobiasMiosczka** [Baeldung/spring-security-registration#47]
Hi @eugenp, im not sure if this is the right place to ask, how could the user enable his account if the token is lost? (The email could have been deleted by spam protection for example.)  What do i have to change in order to let the user resend an e-mail with a new token if he only knows username and password?
Thanks in advance, 
Tobias

**Comment by eugenp** [comment]
Hey @TobiasMiosczka - sure, this is fine (email is better). 
We could potentially add an option to re-send the token, either stand-alone or on the forget password page. We could also simply re-trigger it automatically with no front-end facing option.
