### ISSUE TITLE
Issue when parsing json with field exeption

### ISSUE THREAD

**Issue by NickPel** [Baeldung/spring-security-registration#50]
When i try to check validation of firstName or lastName (I change @Size min = 2 in UserDto.java for firstName and lastName, this is the only way to check these fields validation), validation not working, because of such exeption in lines 125-126 in Registration.html (parsing object, not String):

```
VM52:1 Uncaught SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.m.parseJSON (jquery.min.js:4)
    at Object.<anonymous> (registration.html:125)
    at j (jquery.min.js:2)
    at Object.fireWith [as rejectWith] (jquery.min.js:2)
    at x (jquery.min.js:4)
    at XMLHttpRequest.b (jquery.min.js:4)
```

I saw, that problem is in GenericResponse.java which doesn't have the constructor with "fieldError" argument. Then i saw your other projects and found "The Registration API becomes RESTful" where was such constructor:  

`public GenericResponse(List<FieldError> fieldErrors, List<ObjectError> globalErrors) { }`

Then i added it to my GenericResponse.java and also changed the signature of:

```
protected ResponseEntity<Object> handleBindException(final BindException ex, final HttpHeaders headers, final HttpStatus status, final WebRequest request) {
        logger.error("400 Status Code", ex);
        final BindingResult result = ex.getBindingResult();
        final GenericResponse bodyOfResponse = new GenericResponse(_result.getAllErrors(), "Invalid" + result.getObjectName());
        return handleExceptionInternal(ex, bodyOfResponse, new HttpHeaders(), HttpStatus.BAD_REQUEST, request);
    }
```
for:
```
protected ResponseEntity<Object> handleBindException
  (BindException ex, HttpHeaders headers, HttpStatus status, WebRequest request) {
    logger.error("400 Status Code", ex);
    BindingResult result = ex.getBindingResult();
    GenericResponse bodyOfResponse = 
      new GenericResponse(result.getFieldErrors(), result.getGlobalErrors());
     
    return handleExceptionInternal(
      ex, bodyOfResponse, new HttpHeaders(), HttpStatus.BAD_REQUEST, request);
}
```

Validation works great. But it shows only one warning message also when it has more ones. And i cant use messages_en.properties for changing warn messages texts. 
Please help.

**Comment by lor6** [comment]
Hey @NickPel The issue with only showing one message is on the javascript side. You likely have to replace the html() method for the error field with an append() method.
As far as the validation messages, you need to add a Validator bean in the MVC configuration that explicitly sets the messageSource. Then you can use the message attribute for the validation annotations. Take a look at this PR where these issues are fixed for our project: https://github.com/Baeldung/spring-security-registration/pull/51

**Comment by NickPel** [comment]
Thanks, it works!
