### ISSUE TITLE
Hibernate create-drop

### ISSUE THREAD

**Issue by 1988gadocansey** [Baeldung/spring-security-registration#52]
Hello am kind of wondering if i can change the create-drop property of the hibernate. I don't want my tables to be drop. I want to use this configuration in production

**Comment by lor6** [comment]
Hey @1988gadocansey  You can use update instead of create-drop. The line with create-drop is actually commented in our code. Take a look at the MySql configuration in the persistence.properties file.
Cheers.

**Comment by 1988gadocansey** [comment]
Thanks boss


*Gad Kartey Ocansey*

*Senior Instructor*

*Computer Science Dept*


*Takoradi Polytechnic+233243348522, +233505284060*

*gad.ocansey@tpoly.edu.gh <gad.ocansey@tpoly.edu.gh>*
