### ISSUE TITLE
CSRF Support

### ISSUE THREAD

**Issue by tedwards-rogue** [Baeldung/spring-security-registration#6]
Since this topic covers security and Spring Security has quite a bit of out of the box security features, I am surprised to see CSRF specially disabled in SecSecurityConfig.java.

I have tried to disable it by changing csrf().disable() to just csrf(), but when testing the application goes consistently states session invalid after trying to login and then I finally received the following error:
`There was an unexpected error (type=Forbidden, status=403).
Invalid CSRF Token 'null' was found on the request parameter '_csrf' or header 'X-CSRF-TOKEN'.`

What is your reason for turning off this feature? Have you tried to implement it and could update this application to support it? Maybe a future topic for your site?

Per spring.io:

> When should you use CSRF protection? Our recommendation is to use CSRF protection for any request that could be processed by a browser by normal users. If you are only creating a service that is used by non-browser clients, you will likely want to disable CSRF protection.

**Comment by eugenp** [comment]
@tedwards-rogue That is a good point. 
The reason it's disable is that this particular application is following a series of articles. And, in the articles we didn't yet reach CSRF protection. 
Hope that makes sense. 
Cheers, 
Eugen.

**Comment by tedwards-rogue** [comment]
I appreciate the update. The content of the articles and support code is well written. I have some other tasks first, but I will try to implement CSRF in the near future. Definitely using this application as an example.

**Comment by eugenp** [comment]
Sounds good Ted. If you'd like to pick this one up yourself, I'd be happy to publish it. 
Of course there's a process until that happens. 
Cheers, 
Eugen.
