### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Elieot** [Baeldung/spring-security-registration#74]
Hello
I try to run the app but i get these : (added hibernate dependencies but didn't fix it)
I'm newbie in spring :) 

web - 2018-07-24 15:42:27,177 [main] INFO  o.b.Application - Starting Application v1.0.1-SNAPSHOT on elieot with PID 15532 (C:\Users\NPS\Desktop\E\E2\spring-security-registration-master\target\spring-security
-login-and-registration.war started by NPS in C:\Users\NPS\Desktop\E\E2\spring-security-registration-master\target)
web - 2018-07-24 15:42:27,182 [main] DEBUG o.b.Application - Running with Spring Boot v1.5.1.RELEASE, Spring v4.3.6.RELEASE
web - 2018-07-24 15:42:27,182 [main] INFO  o.b.Application - No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass$3$1 (jar:file:/C:/Users/NPS/Desktop/E/E2/spring-security-registration-master/target/spring-security-login-and-registration.war!/WEB-IN
F/lib/groovy-2.4.7.jar!/) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass$3$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
web - 2018-07-24 15:42:27,907 [background-preinit] INFO  o.h.v.i.u.Version - HV000001: Hibernate Validator 5.3.4.Final
web - 2018-07-24 15:42:29,772 [main] WARN  o.h.v.m.ParameterMessageInterpolator - HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
web - 2018-07-24 15:42:29,952 [main] WARN  o.h.v.m.ParameterMessageInterpolator - HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
web - 2018-07-24 15:42:30,390 [main] INFO  o.a.c.c.StandardService - Starting service Tomcat
web - 2018-07-24 15:42:30,391 [main] INFO  o.a.c.c.StandardEngine - Starting Servlet Engine: Apache Tomcat/8.5.11
web - 2018-07-24 15:42:31,717 [localhost-startStop-1] INFO  o.a.c.c.C.[.[.[/] - Initializing Spring embedded WebApplicationContext
web - 2018-07-24 15:42:32,065 [main] INFO  o.h.j.i.u.LogHelper - HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
web - 2018-07-24 15:42:32,180 [main] INFO  o.h.Version - HHH000412: Hibernate Core {5.3.2.Final}
web - 2018-07-24 15:42:32,182 [main] INFO  o.h.c.Environment - HHH000206: hibernate.properties not found
web - 2018-07-24 15:42:32,271 [main] WARN  o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factor
y.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/baeldung/spring/PersistenceJPAConfig.class]: Invocation of init method failed; nested exception is ja
va.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
web - 2018-07-24 15:42:32,276 [main] WARN  o.s.b.SpringApplication - Error handling failed (Error creating bean with name 'delegatingApplicationListener' defined in class path resource [org/springframework/security/
config/annotation/web/configuration/WebSecurityConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating
 bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionExceptio
n: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available)
web - 2018-07-24 15:42:32,283 [main] ERROR o.s.b.SpringApplication - Application startup failed
o.s.b.f.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/baeldung/spring/PersistenceJPAConfig.class]: Invocation of init method failed; nested exception
 is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at o.s.b.f.s.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
        at o.s.b.f.s.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
        at o.s.b.f.s.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
        at o.s.b.f.s.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at o.s.b.f.s.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        ... 20 frames truncated
Caused by: j.l.NoClassDefFoundError: javax/xml/bind/JAXBException
        at o.h.b.s.XmlMappingBinderAccess.<init>(XmlMappingBinderAccess.java:43)
        at o.h.b.MetadataSources.<init>(MetadataSources.java:86)
        at o.h.j.b.i.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:212)
        at o.h.j.b.i.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:167)
        at o.s.o.j.v.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:54)
        ... 5 frames truncated
        ... 24 common frames omitted
Caused by: j.l.ClassNotFoundException: javax.xml.bind.JAXBException
        at j.n.URLClassLoader.findClass(Unknown Source)
        at j.l.ClassLoader.loadClass(Unknown Source)
        at o.s.b.l.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94)
        at j.l.ClassLoader.loadClass(Unknown Source)
        ... 34 common frames omitted

**Comment by DCampodonico** [comment]
Are you using java 9/10?
Try adding this dependency in pom.xml
`<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.0</version>
</dependency>`

**Comment by lor6** [comment]
@Elieot As @DCampodonico mentioned, this is a Java 9 related error and the fix is above.

Closing.

**Comment by mainakanyi** [comment]
Stii experiencing the same thing and I am using java 8 windows 10 64 bit. @lor6 @DCampodonico @esanchezros @joaonlima Please assist. Kind Regards
