### ISSUE TITLE
i can't found the sql for creating database table

### ISSUE THREAD

**Issue by qiweiview** [Baeldung/spring-security-registration#78]
hello,i can't found the sql for creating database table from the doc,i run the appilication and  the Console output " CommandAcceptanceException Caused by: c.m.j.e.j.MySQLSyntaxErrorException: Table 'registration_02.hibernate_sequence' doesn't exist"

**Comment by qiweiview** [comment]
I found the reason why the table creation failed.
I commented out the database dialect settings and the project can successfully create the table.
![image](https://user-images.githubusercontent.com/35473696/44563545-3967ca80-a791-11e8-984b-e41197a98c34.png)
![image](https://user-images.githubusercontent.com/35473696/44563562-471d5000-a791-11e8-9df6-938b764dda71.png)

**Comment by lor6** [comment]
@qiweiview  Thanks for the info. I've added these fix in the codebase.

Cheers.
