### ISSUE TITLE
I have some problems with the whole project

### ISSUE THREAD

**Issue by DeAngelisLuca** [Baeldung/spring-security-registration#79]
Hi, someone can tell me if importing the project is working with all its use cases. I have several errors such as: password change, login etc.

**Comment by DeAngelisLuca** [comment]
who helps me ? I urgently need this project with these working use cases

**Comment by lor6** [comment]
Hey @DeAngelisLuca I've added some fixes for the login, password reset and registration with captcha pages. Please pull from master and try again.

**Comment by DeAngelisLuca** [comment]
Thank you infinitely you can not imagine how you have changed the day in positive, I saw that you have solved the problems inherent in those use cases, I also wanted to report the problem to change the password when you are authenticated.
Have a nice day 😊

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

________________________________
Da: Loredana Crusoveanu <notifications@github.com>
Inviato: Saturday, September 29, 2018 8:14:51 PM
A: Baeldung/spring-security-registration
Cc: DeAngelisLuca; Mention
Oggetto: Re: [Baeldung/spring-security-registration] I have some problems with the whole project (#79)


Hey @DeAngelisLuca<https://github.com/DeAngelisLuca> I've added some fixes for the login, password reset and registration with captcha pages. Please pull from master and try again.

**Comment by DeAngelisLuca** [comment]
Thank you infinitely you can not imagine how you have changed the day in positive, I saw that you have solved the problems inherent in those use cases, I also wanted to report the problem to change the password when you are authenticated.
Have a nice day 😊

**Comment by DeAngelisLuca** [comment]
I also wanted to report the problem to change the password when you are authenticated.
Loredana can you help me?
Have a nice day 😊

________________________________
Da: Loredana Crusoveanu <notifications@github.com>
Inviato: Sunday, September 30, 2018 11:21:22 PM
A: Baeldung/spring-security-registration
Cc: DeAngelisLuca; Mention
Oggetto: Re: [Baeldung/spring-security-registration] I have some problems with the whole project (#79)


@DeAngelisLuca<https://github.com/DeAngelisLuca> Great, I'll close this one then :)

**Comment by DeAngelisLuca** [comment]
I also wanted to report the problem to change the password when you are authenticated.
Loredana can you help me?
Have a nice day 😊


________________________________
Da: Loredana Crusoveanu <notifications@github.com>
Inviato: Sunday, September 30, 2018 11:21:22 PM
A: Baeldung/spring-security-registration
Cc: DeAngelisLuca; Mention
Oggetto: Re: [Baeldung/spring-security-registration] I have some problems with the whole project (#79)


@DeAngelisLuca<https://github.com/DeAngelisLuca> Great, I'll close this one then :)

**Comment by eugenp** [comment]
Hey @DeAngelisLuca, I think you meant to ping @lor6 here. 
Cheers, 
Eugen.

**Comment by lor6** [comment]
@eugenp The second issue was resolved as well.
