### ISSUE TITLE
How does spring make Autowiring HttpServletRequest inside a singleton thread-safe?

### ISSUE THREAD

**Issue by rhamedy** [Baeldung/spring-security-registration#93]
Hey guys,

Is it thread-safe (how does it work) to `@Autowired` the `HttpServletRequest` inside a `CaptchaService` that is a singleton and not request-scoped bean? 

https://github.com/Baeldung/spring-security-registration/blob/813d3816b28e177108d46a84bfb74f4380adcc84/src/main/java/org/baeldung/captcha/CaptchaService.java#L22

What happens when there are multiple requests using the `CaptchaService` at the same time. Wouldn't introduction of `HttpServletRequest` cause the `CaptchaService` to become stateful? 

I did some googling and came across this [stackoverlfow question](https://stackoverflow.com/questions/48574780/autowired-httpservletrequest-vs-passing-as-parameter-best-practice) that states it's `thread-safe` without providing enough information or supporting documentation and then there is the [experts-exchange](https://www.experts-exchange.com/questions/29081791/Autowired-HttpServletRequest-vs-passing-as-parameter-to-controller.html) where this is discussed without any conclusion. 

Would be nice to hear from the author or anyone with more expertise in the subject matter. Curious how does spring make the `@Autowired private HttpServletRequest` thread-safe inside a `singleton bean`? 

Thanks,

**Comment by maibin** [comment]
@rhamedy first, to answer your question, beans in Spring are not thread-safe. But you shouldn't mix thread-safe with singletons:
https://stackoverflow.com/a/17344009/30608
Next, you can create a thread-safe singleton, but still, it's not considered a valid approach:
https://stackoverflow.com/a/3323374/3060803
