### ISSUE TITLE
Account enumeration

### ISSUE THREAD

**Issue by brampat** [Baeldung/spring-security-registration#94]
As I see it, this example responds with the msg "An account for that username/email already exists. Please enter a different username." on the page if the username and/or email is already taken. That would be an account enumeration vulnerability. Did you plan to leave this out of scope? 

Best practice would be to always accept the registration-form input and use the confirmation email sent to communicate things like double-registration. A user can then be notified with a custom "Someone tried to register an account on this mail-address, but there is already an account" with things like IP, date/time etc. to help investigate possible mis-use / hacking attempt.

**Comment by maibin** [comment]
Thanks for the feedback @brampat. In this article, we just tried to show a basic example, so we won't change it, to not increase the complexity, but we agree with your comment.
