### ISSUE TITLE
Runtime failure Missing EL implementation in maven pom

### ISSUE THREAD

**Issue by dallaybatta** [Baeldung/spring-security-registration#95]
I have have been getting the following error when I start the application

`HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead spring security`

The error seems to complaining about missing of the implementation which I added and it worked.

		<dependency>
		    <groupId>org.glassfish</groupId>
		    <artifactId>javax.el</artifactId>
		    <version>3.0.0</version>
		</dependency>

**Comment by maibin** [comment]
@dallaybatta it should rely only on the javax.el-api dependency - could you try to update your Maven project and then rebuild it?
